apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2019-05-14T21:10:29Z","labels":{"app":"my-nginx"},"name":"my-nginx","namespace":"default","resourceVersion":"214816","selfLink":"/api/v1/namespaces/default/services/my-nginx","uid":"b3959446-768c-11e9-8e83-00505682e2fb"},"spec":{"clusterIP":"10.101.214.220","externalTrafficPolicy":"Cluster","ports":[{"name":"8080-80","nodePort":31000,"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app":"my-nginx"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-05-14T21:10:29Z"
  labels:
    app: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "298615"
  selfLink: /api/v1/namespaces/default/services/my-nginx
  uid: b3959446-768c-11e9-8e83-00505682e2fb
spec:
  clusterIP: 10.101.214.220
  externalTrafficPolicy: Cluster
  ports:
  - name: 8080-80
    nodePort: 30058 
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
