# encode Secret manually
# echo 'Fernando Hood' | base64
#  RmVybmFuZG9Ib29k 

# create a Secret via configuration file, put encoded Secret into the file
# cat create-secret_from-file.yaml
apiVersion: v1
kind: Secret
metadata:
  name: name-token
type: Opaque
data:
  hendy: RmVybmFuZG9Ib29k 

#// create the resource
# kubectl create-secret-from-file.yaml
#secret "name-token" created